--- 
abstract: LWP methods implementation with Curl engine
author: Lindolfo Rodrigues de Oliveira Neto <lorn@cpan.org>
build_requires: 
  Carp: 0
  HTML::Entities: 0
  Test::More: 0
  WWW::Curl::Easy: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: LWP-Curl
no_index: 
  directory: 
    - inc
    - t
version: 0.05
